## Embeddings

Embeddings are a numerical representation of a text. Basically a list of floating point numbers. 
`Why?`
Machine learnign models dont use text for training or any of the calculations. They need numbers. Embeddings provides us with that feature.  
these embeddings are used for semantic searches meaning 2 embedding swith relatively same value have similar semantic meaning which means for example `COW` and `Animal` will be close to each other int he vector space.  
But `COW` and `Airplane` will be dar away from each other since they dont have semantic meaning.  
There are many models which help in converting the test into embeddings and we can use the apis to convert the text into embeddings with couple of lines of code.

In [7]:
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(), override=True)

import pandas as pd
df = pd.read_csv('words.csv')
df = df.sample(frac=1)
df

          text
24    sandwich
13     raccoon
21        milk
38       green
30       pizza
19      lizard
39        gray
6       rabbit
37  guinea pig
10  cappuccino
26        fish
3       purple
11        deer
32       pasta
25      coyote
0          fox
17        wolf
14     hamster
1      opossum
5       coffee
4       badger
29       salad
35       white
16      ferret
41      orange
27         dog
7         hare
22         tea
2        black
15      burger
12        bird
36         cat
40       water
33      turtle
18    squirrel
31       snake
23        blue
20         red
34       brown
8         soda
9       yellow
28        bear

In [8]:
from openai import OpenAI
def get_embedding(text, model='text-embedding-3-small'):
    client = OpenAI()
    text = text.replace('\n', ' ')
    response = client.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [9]:
df['embedding'] = df['text'].apply(lambda x: get_embedding(x))

In [10]:
df

          text                                          embedding
24    sandwich  [-0.00571441650390625, -0.048858642578125, -0....
13     raccoon  [0.05898793041706085, -0.0010472146095708013, ...
21        milk  [0.039642333984375, -0.004215240478515625, -0....
38       green  [0.006280624307692051, -0.0011062989942729473,...
30       pizza  [-0.010169987566769123, -0.028292447328567505,...
19      lizard  [0.01209514494985342, -0.012445430271327496, -...
39        gray  [0.004851989448070526, -0.02022680640220642, -...
6       rabbit  [0.006238460540771484, -0.01577582396566868, 0...
37  guinea pig  [0.0074920654296875, -0.0266571044921875, 0.00...
10  cappuccino  [-0.0248565673828125, -0.0309295654296875, -0....
26        fish  [-0.0026927476283162832, -0.021741770207881927...
3       purple  [0.0247344970703125, -0.03472900390625, -0.026...
11        deer  [0.060791015625, -0.032928466796875, 0.0036182...
32       pasta  [-0.05015381798148155, -0.04086881875991821, 0...
25      coyote  [0.0401611328125, -0.031219482421875, -0.01911...
0          fox  [-0.03349066898226738, 0.0015862904256209731, ...
17        wolf  [-0.0030059814453125, -0.0266571044921875, 0.0...
14     hamster  [0.03875732421875, -0.0274200439453125, 0.0297...
1      opossum  [0.031982421875, 0.03253173828125, -0.02006530...
5       coffee  [-0.01006317138671875, 0.0037403106689453125, ...
4       badger  [0.021669577807188034, -0.022312505170702934, ...
29       salad  [-0.0007352828979492188, -0.037078857421875, 0...
35       white  [0.0032487320713698864, -0.02826567552983761, ...
16      ferret  [0.006313289050012827, -0.04182418808341026, -...
41      orange  [-0.0258636474609375, -0.005527496337890625, -...
27         dog  [0.051116943359375, -0.018707275390625, -0.004...
7         hare  [0.018302442505955696, -0.022041788324713707, ...
22         tea  [-0.016386866569519043, -0.030908560380339622,...
2        black  [0.01116943359375, -0.012054443359375, -0.0193...
15      burger  [-0.035552978515625, -0.0159912109375, 0.00167...
12        bird  [0.056549072265625, -0.00104522705078125, 0.00...
36         cat  [0.02557373046875, -0.023406982421875, -0.0160...
40       water  [0.0030422210693359375, 0.0174560546875, -0.01...
33      turtle  [0.02813720703125, -0.016265869140625, 0.01115...
18    squirrel  [0.033203125, -0.04071044921875, -0.0200500488...
31       snake  [0.051055908203125, -0.0201416015625, -0.03671...
23        blue  [-0.0010865783551707864, -0.016484010964632034...
20         red  [-0.02211996167898178, -0.010933708399534225, ...
34       brown  [-0.03070068359375, -0.007198333740234375, 0.0...
8         soda  [0.0184783935546875, -0.025054931640625, -0.03...
9       yellow  [-0.01422119140625, -0.01800537109375, 0.02735...
28        bear  [0.046112060546875, -0.0170745849609375, -0.02...

In [11]:
df.to_csv('words_embeddings.csv', index=False)

### Estimating embedding costs with tiktoken

In [12]:
import tiktoken
import pandas as pd

df = pd.read_csv('words_embeddings.csv')
df.head()

       text                                          embedding
0  sandwich  [-0.00571441650390625, -0.048858642578125, -0....
1   raccoon  [0.05898793041706085, -0.0010472146095708013, ...
2      milk  [0.039642333984375, -0.004215240478515625, -0....
3     green  [0.006280624307692051, -0.0011062989942729473,...
4     pizza  [-0.010169987566769123, -0.028292447328567505,...

In [13]:
words = list(df['text'])
words[:10]

['sandwich',
 'raccoon',
 'milk',
 'green',
 'pizza',
 'lizard',
 'gray',
 'rabbit',
 'guinea pig',
 'cappuccino']

In [15]:
enc = tiktoken.encoding_for_model('text-embedding-3-small')
total_tokens = sum([len(enc.encode(word)) for word in words])
print(total_tokens)

62

In [17]:
cost_per_token = 0.02/1000000
estimated_cost = total_tokens * cost_per_token
print(f'Cost of embedding {total_tokens} tokens: ${estimated_cost:0.10f}')

Cost of embedding 62 tokens: $0.0000012400

### Performing Semantic Searches

In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('words_embeddings.csv')
df.head()

       text                                          embedding
0  sandwich  [-0.00571441650390625, -0.048858642578125, -0....
1   raccoon  [0.05898793041706085, -0.0010472146095708013, ...
2      milk  [0.039642333984375, -0.004215240478515625, -0....
3     green  [0.006280624307692051, -0.0011062989942729473,...
4     pizza  [-0.010169987566769123, -0.028292447328567505,...

In [20]:
df['embedding'] = df['embedding'].apply(eval).apply(np.array)

In [23]:
search_term = 'red'
search_term_vector = get_embedding(search_term)
def cosine_similarity(vector_a, vector_b):
    dot_product = np.dot(vector_a, vector_b)
    magnitude_a = np.linalg.norm(vector_a, 2) # L2 norm
    magnitude_b = np.linalg.norm(vector_b, 2) # L2 norm
    
    if magnitude_a == 0 or magnitude_b == 0:
        return 0 # Or handle as appropriate for your application
        
    cosine_similarity = dot_product / (magnitude_a * magnitude_b)
    return cosine_similarity

df['similarities'] = df['embedding'].apply(lambda x: cosine_similarity(x, search_term_vector))
df.sort_values('similarities', ascending=False).head(10)

      text                                          embedding  similarities
37     red  [-0.02211996167898178, -0.010933708399534225, ...      0.999999
36    blue  [-0.0010865783551707864, -0.016484010964632034...      0.641060
11  purple  [0.0247344970703125, -0.03472900390625, -0.026...      0.565471
22   white  [0.0032487320713698864, -0.02826567552983761, ...      0.547506
24  orange  [-0.0258636474609375, -0.005527496337890625, -...      0.544711
12    deer  [0.060791015625, -0.032928466796875, 0.0036182...      0.504806
6     gray  [0.004851989448070526, -0.02022680640220642, -...      0.503979
28   black  [0.01116943359375, -0.012054443359375, -0.0193...      0.485274
38   brown  [-0.03070068359375, -0.007198333740234375, 0.0...      0.481777
15     fox  [-0.03349066898226738, 0.0015862904256209731, ...      0.473181

In [24]:
df

,text,embedding,similarities
0,sandwich,"[-0.00571441650390625, -0.048858642578125, -0....",0.207916
1,raccoon,"[0.05898793041706085, -0.0010472146095708013, ...",0.313692
2,milk,"[0.039642333984375, -0.004215240478515625, -0....",0.216576
3,green,"[0.006280624307692051, -0.0011062989942729473,...",0.458701
4,pizza,"[-0.010169987566769123, -0.028292447328567505,...",0.248450
5,lizard,"[0.01209514494985342, -0.012445430271327496, -...",0.298842
6,gray,"[0.004851989448070526, -0.02022680640220642, -...",0.503979
7,rabbit,"[0.006238460540771484, -0.01577582396566868, 0...",0.393911
8,guinea pig,"[0.0074920654296875, -0.0266571044921875, 0.00...",0.203466
9,cappuccino,"[-0.0248565673828125, -0.0309295654296875, -0....",0.183713
10,fish,"[-0.0026927476283162832, -0.021741770207881927...",0.296918
11,purple,"[0.0247344970703125, -0.03472900390625, -0.026...",0.565471
12,deer,"[0.060791015625, -0.032928466796875, 0.0036182...",0.504806
13,pasta,"[-0.05015381798148155, -0.04086881875991821, 0...",0.232130
14,coyote,"[0.0401611328125, -0.031219482421875, -0.01911...",0.277190
15,fox,"[-0.03349066898226738, 0.0015862904256209731, ...",0.473181
16,wolf,"[-0.0030059814453125, -0.0266571044921875, 0.0...",0.338572
17,hamster,"[0.03875732421875, -0.0274200439453125, 0.0297...",0.239109
18,opossum,"[0.031982421875, 0.03253173828125, -0.02006530...",0.210759
19,coffee,"[-0.01006317138671875, 0.0037403106689453125, ...",0.300802
20,badger,"[0.021669577807188034, -0.022312505170702934, ...",0.335450
21,salad,"[-0.0007352828979492188, -0.037078857421875, 0...",0.305179
22,white,"[0.0032487320713698864, -0.02826567552983761, ...",0.547506
23,ferret,"[0.006313289050012827, -0.04182418808341026, -...",0.308749
24,orange,"[-0.0258636474609375, -0.005527496337890625, -...",0.544711
25,dog,"[0.051116943359375, -0.018707275390625, -0.004...",0.343204
26,hare,"[0.018302442505955696, -0.022041788324713707, ...",0.388754
27,tea,"[-0.016386866569519043, -0.030908560380339622,...",0.304714
28,black,"[0.01116943359375, -0.012054443359375, -0.0193...",0.485274
29,burger,"[-0.035552978515625, -0.0159912109375, 0.00167...",0.312457
30,bird,"[0.056549072265625, -0.00104522705078125, 0.00...",0.340236
31,cat,"[0.02557373046875, -0.023406982421875, -0.0160...",0.279177
32,water,"[0.0030422210693359375, 0.0174560546875, -0.01...",0.293589
33,turtle,"[0.02813720703125, -0.016265869140625, 0.01115...",0.305454
34,squirrel,"[0.033203125, -0.04071044921875, -0.0200500488...",0.245489
35,snake,"[0.051055908203125, -0.0201416015625, -0.03671...",0.283541
36,blue,"[-0.0010865783551707864, -0.016484010964632034...",0.641060
37,red,"[-0.02211996167898178, -0.010933708399534225, ...",0.999999
38,brown,"[-0.03070068359375, -0.007198333740234375, 0.0...",0.481777
39,soda,"[0.0184783935546875, -0.025054931640625, -0.03...",0.291044
40,yellow,"[-0.01422119140625, -0.01800537109375, 0.02735...",0.438650
41,bear,"[0.046112060546875, -0.0170745849609375, -0.02...",0.343332

In [25]:
v1 = df['embedding'].iloc[2] # Milk
v2 = df['embedding'].iloc[9] # Cappucino
v = v1 + v2
df['similarities'] = df['embedding'].apply(lambda x: cosine_similarity(x, v))
df.sort_values('similarities', ascending=False).head(10)

,text,embedding,similarities
9,cappuccino,"[-0.0248565673828125, -0.0309295654296875, -0....",0.829932
2,milk,"[0.039642333984375, -0.004215240478515625, -0....",0.829802
19,coffee,"[-0.01006317138671875, 0.0037403106689453125, ...",0.507596
13,pasta,"[-0.05015381798148155, -0.04086881875991821, 0...",0.451773
39,soda,"[0.0184783935546875, -0.025054931640625, -0.03...",0.443256
27,tea,"[-0.016386866569519043, -0.030908560380339622,...",0.409103
0,sandwich,"[-0.00571441650390625, -0.048858642578125, -0....",0.378766
21,salad,"[-0.0007352828979492188, -0.037078857421875, 0...",0.343140
32,water,"[0.0030422210693359375, 0.0174560546875, -0.01...",0.335403
22,white,"[0.0032487320713698864, -0.02826567552983761, ...",0.334551