In [2]:
import pandas as pd
df = pd.read_csv('website_traffic_data.csv')

In [3]:
df

      Source  SessionDuration
0    Organic             8.15
1    Organic            17.28
2     Direct             8.62
3       Paid            17.95
4       Paid            27.04
..       ...              ...
95  Referral            24.42
96  Referral             6.52
97      Paid             3.81
98    Direct            13.50
99      Paid            13.28

[100 rows x 2 columns]

In [5]:
grouped_data = df.groupby('Source')
average_duration = grouped_data['SessionDuration'].mean()
average_duration

Source
Direct      15.151364
Organic     16.472609
Paid        12.542083
Referral    14.485333
Social      17.070625
Name: SessionDuration, dtype: float64

### Analyzing traffic Data with Datetime

In [6]:
df = pd.read_csv('website_traffic_data_datetime.csv')
df

      Source  SessionDuration  Visits        Date
0     Direct            27.53     267  2023-01-01
1   Referral            25.65     476  2023-01-02
2     Social            14.03     441  2023-01-03
3   Referral             3.77     473  2023-01-04
4   Referral            11.75     434  2023-01-05
..       ...              ...     ...         ...
95    Social             3.79     226  2023-04-06
96  Referral            28.28     277  2023-04-07
97      Paid            12.53     286  2023-04-08
98      Paid            16.01      97  2023-04-09
99   Organic            25.29     284  2023-04-10

[100 rows x 4 columns]

In [9]:
df.dtypes

Source                        str
SessionDuration           float64
Visits                      int64
Date               datetime64[us]
dtype: object

In [8]:
df['Date'] = pd.to_datetime(df['Date'])

In [10]:
df.set_index('Date', inplace=True)

In [11]:
df

              Source  SessionDuration  Visits
Date
2023-01-01    Direct            27.53     267
2023-01-02  Referral            25.65     476
2023-01-03    Social            14.03     441
2023-01-04  Referral             3.77     473
2023-01-05  Referral            11.75     434
...              ...              ...     ...
2023-04-06    Social             3.79     226
2023-04-07  Referral            28.28     277
2023-04-08      Paid            12.53     286
2023-04-09      Paid            16.01      97
2023-04-10   Organic            25.29     284

[100 rows x 3 columns]

In [14]:
monthly_visits = df["Visits"].resample('ME').sum()

In [15]:
monthly_visits

Date
2023-01-31    7813
2023-02-28    7137
2023-03-31    8384
2023-04-30    2233
Freq: ME, Name: Visits, dtype: int64